name: linux_build

# Run CI on
# - each push
# - each pull request
# - scheduled weekly
on:
  push:
    branches-ignore:
    - ganesh_dev
  pull_request:
  schedule:
    - cron: '0 0 * * 0 ' # weekly

# Environment variables
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  MAKEFLAGS: "-j8"

# Multiple job to tests
jobs:
  # Test the compilation compatibility
  linux_build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    # Branch on different OS and settings
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Quick Test: GCC-8 (Ubuntu 18.04)",
            artifact: "OpenFPGA-basic-tests-ubuntu-18.04-gcc8-build.7z",
            os: ubuntu-18.04,
            cc: "gcc-8", cxx: "g++-8",
            reg_script: "quick_test.sh"
          }

    # Define the steps to run the build job
    steps:
      - name: Checkout Skywater-OpenFPGA repo
        uses: actions/checkout@v2

      - name: Checkout OpenFPGA repo
        uses: actions/checkout@v2
        with:
          repository: lnis-uofu/OpenFPGA
          path: OpenFPGA

      - name: Install dependency
        run: source ./.github/workflows/install_dependency.sh 

      - name: Checkout CMake version
        run: cmake --version 

      - name: Checkout iVerilog version
        run: |
          iverilog -V 
          vvp -V 

      - name: Create CMake build environment
        # Some projects don't allow in-source building, so create a separate build directory
        # We'll use this as our working directory for all subsequent commands
        run: cmake -E make_directory ${{runner.workspace}}/OpenFPGA/build

      - name: Configure CMake
        # Use a bash shell so we can use the same syntax for environment variable
        # access regardless of the host operating system
        shell: bash
        working-directory: ${{runner.workspace}}/OpenFPGA/build
        # Note the current convention is to use the -S and -B options here to specify source 
        # and build directories, but this is only available with CMake 3.13 and higher.  
        # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
        run: |
          export CC=${{ matrix.config.cc }}
          export CXX=${{ matrix.config.cxx }}
          cmake $GITHUB_WORKSPACE/OpenFPGA -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        working-directory: ${{runner.workspace}}/OpenFPGA/build
        shell: bash
        # Execute the build.  You can specify a specific target with "--target <NAME>"
        run: |
          cmake --build . --config $BUILD_TYPE 

      - name: ${{matrix.config.name}}
        if: contains(matrix.config.name, 'Quick Test')
        shell: bash
        # Execute the test. 
        run: source ./.github/workflows/${{matrix.config.reg_script}}
