name: To perform precheck and deploy to release repository

on:
  push:
  pull_request:
    types: closed
    branches:
      - master
jobs:
  linux:
    name: Updating release repository
    runs-on: ubuntu-latest

    steps:
    - name: Checkout SOFA-Chips
      uses: actions/checkout@v2
      with:
        path: SOFA-Chips

    - name: Checkout Caravel-SOFA-HD
      uses: actions/checkout@master
      with:
        repository: ganeshgore/dummyTestRepo
        # repository: lnis-uofu/Caravel-SOFA-HD
        token: ${{ secrets.GITHUB_TOKEN }}
        path: Caravel-SOFA-HD

    - name: Updating files
      run: pwd && ls && source ./.github/workflows/sync_repo.sh

    - name: Commit files
      working-directory: ${{ runner.workspace }}/Caravel-SOFA-HD
      run: |
        git config --local user.email "lnis.uofu@github.com"
        git config --local user.name "lnis.uofu"
        cd Caravel-SOFA-HD
        git commit -m "Auto commit" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        directory: Caravel-SOFA-HD
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
